spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pw
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: public
    drop-first: false